var unescoSites = [
    { title: "Statue of Liberty, New York City, USA" },
    { title: "Independence Hall, Philadelphia, USA" },
    { title: "Guggenheim Museum, New York City, USA" },
    { title: "Schönbrunn Palace, Vienna, Austria" },
    { title: "Historic Centre of the City of Salzburg, Austria" },
    { title: "Historic Centre of Vienna, Austria" },
    { title: "Grand Palace, Brussels, Belgium" },
    { title: "Belfries of Belgium and France" },
    { title: "Historic District of Old Quebec, Canada" },
    { title: "Historic Cairo, Egypt" },
    { title: "Banks of the Seine, Paris, France" },
    { title: "Budapest, Hungary" },
    { title: "Historic Centre of Rome, Italy" },
    { title: "Historic Centre of Mexico City, Mexico" },
    { title: "Pre-Hispanic City of Chichen Itza, Mexico" },
    { title: "Historic Centre of San Francisco de Campeche, Mexico" },
    { title: "Røros Mining Town, Norway" },
    { title: "Panama Viejo, Panama" },
    { title: "Historic Centre of Krakow, Poland" },
    { title: "Historic Centre of Cordoba, Spain" },
    { title: "Works of Antoni Gaudí, Barcelona, Spain" },
    { title: "Historic Areas of Istanbul, Turkey" },
    { title: "Tower of London, UK" },
    { title: "Yosemite National Park, USA" },
    { title: "San Antonio Missions, USA" },
];
